Repository WorldEnterpriseGroup/silkcorp, pull requests merged in 2023-04, with the labels that each got.

#117 WHO WE ARE
  index.html
Labels: documentation, content writing, copywriting

#126 Updated Space
  index.html
Labels: documentation, copywriting

#138 VP of Franchise Development Message
  index.html
Labels: documentation, content writing

#139 OUR TEAM 3rd Image Text
  index.html
Labels: copywriting

#140 CSS of Get in Touch Form
  css/style.css
  index.html
Labels: documentation, enhancement

#142 Updated Values
  index.html
  js/script.js
Labels: enhancement

#144 I have worked on it#128
  index.html
Labels: enhancement, help wanted, content writing

#145 Rearrange #SILKLife images and text
  index.html
Labels: documentation, enhancement, copywriting, media content

#150 Deleted the description issue#SILKLife Description #149
  index.html
Labels: enhancement, copywriting

#153 Turned Footer Logo White
  img/silkcorpwhite.svg
  index.html
Labels: enhancement, media content

#152 Updated the second VP message in the issue#147.
  index.html
Labels: documentation, copywriting

#155 Created a .md file under issue#151
  SILK Franchise Opportunity.md
Labels: documentation, enhancement, content writing

#157 Created a file for Franchise agreement issue#154.
  Franchise agreement template.md
Labels: documentation, content writing

#163 Create a .md file under issue #160
  Silk Yacht SLA.md
Labels: documentation, enhancement, content writing, copywriting

#164 create an .md file under issue #158
  Silk YACHT services.md
Labels: documentation, enhancement, content writing, copywriting

#165 Created .md file for Services offerings plan issue#159.
  Services offerings plan.md
Labels: documentation, enhancement, content writing

#166 Created a file for all agreements issue#162.
  Paperwork checklist.md
Labels: documentation, enhancement, content writing

#167 Template for lease agreement issue#154.
  Lease agreement template.md
Labels: documentation, enhancement, content writing, copywriting

#168 Financial Disclosure template issue#154.
  Financial Disclosures.md
Labels: documentation, enhancement, content writing, copywriting
